--Erzeugt 24Datensätze für D_Zeit
INSERT INTO DWH_BackZeit.dbo.D_Zeit (Stunde, Tageszeit)
VALUES
('00', 'Nacht'),
('01', 'Nacht'),
('02', 'Nacht'),
('03', 'Nacht'),
('04', 'Nacht'),
('05', 'Nacht'),
('06', 'Morgen'),
('07', 'Morgen'),
('08', 'Morgen'),
('09', 'Morgen'),
('10', 'Vormittag'),
('11', 'Vormittag'),
('12', 'Mittag'),
('13', 'Mittag'),
('14', 'Mittag'),
('15', 'Nachmittag'),
('16', 'Nachmittag'),
('17', 'Nachmittag'),
('18', 'Abend'),
('19', 'Abend'),
('20', 'Abend'),
('21', 'Abend'),
('22', 'Nacht'),
('23', 'Nacht');